function loadingBar(i, max, f)
%LOADINGBAR A simple loading bar for the processing of loops.
% Designed to use in a for loop, and in conjuction with the function
% "initializeLoadingBar".
% Run the "initalizeLoadingBar" outside of the for loop and set equal to a
% variable (This is the loading bar figure.)
% Input the increment i and the variable for the end of the for loop
% i.e. number of iterations.

displayNotes = 1;
inc = floor(max/max);
message = strcat('Loading...', num2str(i), "/", num2str(max));

if(mod(i, inc) == 0)
    progress = i / max;
    waitbar(progress, f, message);
end
if(mod(i, 20) == 0 && displayNotes)
    quotes = ...
        {'You will find your way, you can go the distance!',...
        'Don''t worry, only 5 billion more calculations!',...
        'I talked to your computer, it''s begging for mercy.',...
        'WARNING: Program will terminate unless computer is given cupcakes.',...
        'It should be any second now...',...
        'I''m sorry, Kate. I''m afraid I can''t do that.',...
        'What''s brown and rhymes with Snoop? Dr. Dre.',...
        'How do you think the unthinkable? With an itheberg.',...
        'Only a few more to go!',...
        'This might take a while, but everything is going according to plan.',...
        'Kevin Durant is a snake.',...
        'Still waiting...',...
        'Just a couple more calculations...',...
        'Not sure, but this might take a little bit of time.',...
        'When the going gets tough, the tough go drinking.',...
        'If Britney Spears can get through 2007, you can get through today.',...
        'If you can believe in Santa for like 8 years, you can believe in yourself for like 5 minutes.',...
        'What are you waiting for? DO IT!',...
        'Don''t let your dreams be dreams.',...
        'Congratulations! Your prize is 10 minutes of wasted time.',...
        'Deleting text files...',...
        'Deleting computer programs...',...
        'Solving the Fermi paradox...',...
        'Downloading more RAM...',...
        'Hang in there!',...
        'Solving world hunger...',...
        'Eating Oreos without separating them...',...
        'Finding El Dorado...',...
        'Solving time loops...',...
        'Patching glitches in the matrix...',...
        'Finding Waldo...',...
        'Busting through the wall and saying "Oh yeah"...',...
        'Buying girl scout cookies...',...
        'Preheating oven...',...
        'Calculating mark needed to get an A...',...
        'Beginning mental breakdown...',...
        'Wondering if the universe is truly infinite...',...
        'Eating breakfast for dinner...',...
        'Blasting inappropriate songs in the library...',...
        'Procrastinating doing actual work...',...
        'Watching YouTube videos until 3am...',...
        'Sliding into DMs...',...
        'Watching YouTube tutorials...',...
        'Processing if-else statements...',...
        'Processing your data, but in a slower yet cooler fashion...'...
        };
    
    [~, listSize] = size(quotes);
    n = floor(rand * listSize) + 1;
    disp(quotes(n));
    
end

if (i == max)
    close(f);
end

end

